[package]
name = "bit_weaving"
version = "0.1.0"
authors = ["muthu", "surya"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
byteorder = "1"
nix = "0.15.0"
packed_simd = "0.3.3"
